const express = require('express');
const router = express.Router();

const authRouter = require('./auth');
const n8nRouter = require('./n8n');
const deployRouter = require('./deploy');
const credentialRouter = require('./credential');
const repoRouter = require('./repo');
const reportRouter = require('./report');
const chatRouter = require('./chat');
const complianceRouter = require('./compliance');
const oauthRouter = require('./oauth');
const securityScanRouter = require('./securityScan');
const performanceRouter = require('./performance');
const wafScanRouter = require('./wafScan');
const awsRouter = require('./aws');
const healthMonitorRouter = require('./healthMonitor');
const userEmailRouter = require('./userEmail');
const albRouter = require('./alb');
const albAccountSettingsRouter = require('./albAccountSettings');
const slackIntegrationRouter = require('./slack');
const userTargetSelectionsRouter = require('./userTargetSelections');
const albAutoActionsRouter = require('./albAutoActions');
const albAutoDeregisterActivityRouter = require('./albAutoDeregisterActivity');

router.use('/auth', authRouter);
router.use('/n8n', n8nRouter);
router.use('/deploy', deployRouter);
router.use('/credential', credentialRouter);
router.use('/repo', repoRouter);
router.use('/report', reportRouter);
router.use('/chat', chatRouter);
router.use('/redirect', complianceRouter);
router.use('/oauth', oauthRouter);
router.use('/security-scan', securityScanRouter);
router.use('/performance', performanceRouter);
router.use('/waf-scan', wafScanRouter);
router.use('/aws', awsRouter);
router.use('/health-monitor', healthMonitorRouter);
router.use('/user-email', userEmailRouter);
router.use('/alb', albRouter);
router.use('/alb-account-settings', albAccountSettingsRouter);
router.use('/slack', slackIntegrationRouter);
router.use('/user', userTargetSelectionsRouter);
router.use('/alb/auto-actions', albAutoActionsRouter);
router.use('/alb/auto-deregister-activity', albAutoDeregisterActivityRouter);

module.exports = router;
